name: Auto approve

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'michbud98' #michbud98 a mbudik-cen66499
      with:
        github-token: ${{ secrets.AUTOAPPROVE_KEY }}